name: Deploy site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  export:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      KOBWEB_CLI_VERSION: 0.9.21
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Export site
        run: |
          ./gradlew :site:kobwebExport --no-daemon

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.kobweb/site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2